themes:
  - name: "monokai-custom"
    colors:
      - "#1E1F1C"
      - "#272822"
      - "#414339"
      - "#75715E"
      - "#88846F"
      - "#F8F8F2"
      - "#F92672"
      - "#A6E22E"
      - "#A6E22E"
      - "#819AFF"
      - "#AE81FF"
      - "#66D9EF"
      - "#C4265E"
      - "#86B42B"
      - "#B3B42B"
      - "#6A7EC8"
      - "#8C6BC8"
      - "#56ADBC"
